### ISSUE TITLE
tf.erb filename must have underscores, not hyphens

### ISSUE THREAD

**Issue by betsy-lichtenberg** [msampathkumar/MagicModules-TerraformTools#5]
Hi Sampath,

Can we force the tf.erb output filename to have underscores instead of hyphens?

Please see that all filenames have underscores here:
https://github.com/GoogleCloudPlatform/magic-modules/tree/master/mmv1/templates/terraform/examples

Also note that @rileykarson said:

```
Noticed this line's probably gotta use underscores instead of hyphens. It causes the generated test to create invalid Go code.

In mmv1/products/vpcaccess/terraform.yaml:

> @@ -31,6 +31,16 @@ overrides: !ruby/object:Overrides::ResourceOverrides

         min_version: beta

         vars:

           name: "vpc-con"

+      - !ruby/object:Provider::Terraform::Examples

+        name: "cloudrun-vpc-access-connector"

⬇️ Suggested change
-        name: "cloudrun-vpc-access-connector"

+        name: "cloudrun_vpc_access_connector"
```

Thanks,
Betsy

**Comment by msampathkumar** [comment]
@betsy-lichtenberg sure. I might have to update the test-cases as well. Let me fix it and update you!

**Comment by msampathkumar** [comment]
@betsy-lichtenberg  - Updated the .yaml generation code, to have filenames to be defined in `_` rather than `-` . Other Test cases also seem to be passed. If you encounter any issues, please check & advice. Thank you.

**Comment by betsy-lichtenberg** [comment]
Thanks!
